### ISSUE TITLE
Dinner Issue

### ISSUE THREAD

**Issue by dpugh1993** [IntroToCode/Spring22_Recipes_Codemates8#1]
## 💬 Discussion topic

Yo Team, what should we have for dinner?

## ❗ Potential issues

Vegetarian, chicken, fish or...?

## 👥 People to consult

@peterbobseine @bacarter94 @ryangibo @luisfego @CMason999 @joewadcan 

## 📃 Details

Duck confit with lentils

**Comment by CMason999** [comment]
@dpugh1993 Fancy, I like it. Who is coming to dinner? 4 people?

**Comment by bacarter94** [comment]
How about pairing a Malbec with the duck @dpugh1993

**Comment by peterbobseine** [comment]
I second the Malbec

**Comment by ryangibo** [comment]
I have never had duck confit but open to it! Yes on the Malbec! 🍷🍷
