### ISSUE TITLE
Lunch Issue

### ISSUE THREAD

**Issue by peterbobseine** [IntroToCode/Spring22_Recipes_Codemates8#2]
## 💬 Discussion topic

What should we make for lunch?

## ❗ Potential issues

Are there any allergies or food restrictions for anyone in the group? I'm feeling ham sammys. 

## 👥 People to consult

@CMason999 @ryangibo @dpugh1993 @bacarter94 @luisfego @joewadcan 

## 📃 Details

Are we good with ham sammys? Wheat bread, mayo, ham, American cheese, and lettuce

**Comment by CMason999** [comment]
@peterbobseine I'm more of a turkey gal myself, can we do a ham/turkey club?

**Comment by bacarter94** [comment]
Swiss cheese please!

**Comment by dpugh1993** [comment]
I prefer red leaf lettuce....thanks!

**Comment by peterbobseine** [comment]
Turkey, swiss cheese, and red lead have been added! Along with bacon...

**Comment by bacarter94** [comment]
😋

**Comment by ryangibo** [comment]
Love the Turkey/ham combo + Swiss. Bacon a must!! ❤️
