### ISSUE TITLE
Breakfast Discussion

### ISSUE THREAD

**Issue by CMason999** [IntroToCode/Spring22_Recipes_Codemates8#3]
## 💬 Discussion topic
What should we make for breakfast?

## ❗ Potential issues

Savory or sweet?
How many people do we want to serve?
Is it healthy? Is it boozy?

## 👥 People to consult

@peterbobseine @ryangibo @dpugh1993 @bacarter94 @luisfego @joewadcan 
Note: Srinivas Mantha is MIA (not in class?)

## 📃 Details

I love breakfast tacos and mimosas.

**Comment by dpugh1993** [comment]
Savory and mimosas for sure

**Comment by bacarter94** [comment]
Savory *and* sweet! +1 for mimosas

**Comment by peterbobseine** [comment]
breakfast bloody marys please

**Comment by ryangibo** [comment]
Chicken and waffles +1 to mimosas!
